name: automerge check

on:
  pull_request:
    types:
      - labeled
  check_suite:
    types:
      - completed

permissions:
  checks: read
  contents: write
  actions: write
  statuses: read
  security-events: read

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
          MERGE_LABELS: "merge"
          LOG: "TRACE"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          UPDATE_LABELS: "merge"
          UPDATE_METHOD: "rebase"
          MERGE_FORKS: "false"
