name: automerge check

on:
  pull_request:
    types:
      - labeled
  check_suite:
    types:
      - completed

permissions:
  actions: write
  checks: read
  contents: write
  deployments: write
  pull-requests: write
  repository-projects: write
  security-events: read
  statuses: read

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
          MERGE_LABELS: "merge"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          UPDATE_LABELS: "merge"
          UPDATE_METHOD: "rebase"
          MERGE_FORKS: "false"
